#!/bin/bash

if [ "$GOGUI" == "" ]; then
    export GOGUI="$HOME/prg/go/gogui-1.4.9/bin"
fi

export GOGUI_REGRESS="$GOGUI/gogui-regress"
$GOGUI_REGRESS "./michi gtp" -output tests/output $1 tests/fix_atari.tst 
$GOGUI_REGRESS "./michi gtp" -output tests/output $1 tests/large_pat.tst 
$GOGUI_REGRESS "./michi gtp" -output tests/output $1 tests/board.tst 
$GOGUI_REGRESS "./michi gtp" -output tests/output $1 tests/undo.tst 
